<a href="https://colab.research.google.com/github/sesme100/Deep_Learning/blob/master/backpropagation_%EB%AF%B8%EB%B6%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
# 참고사이트 https://s3.us-west-2.amazonaws.com/secure.notion-static.com/d7324237-68ae-4bc1-a7ad-fa76bdcc0491/practice_xor.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAT73L2G45II2TX57K%2F20190712%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20190712T105625Z&X-Amz-Expires=86400&X-Amz-Security-Token=AgoJb3JpZ2luX2VjEF8aCXVzLXdlc3QtMiJHMEUCIQCN7cc%2FPBXAg%2BXaN9d5jEx8ey9uDcOCX6L0xNlfCkYL9gIgGvwdaBqIJpTWAU0dHN8fl5yOQg7DIuRJB1g%2FfZWNAVQq4wMIuP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgwyNzQ1NjcxNDkzNzAiDCFT9hTioSOkygEL5iq3A5NHkJ%2FMF27JU9Q9wouEzeAdBdE5yE8SaTN2V6eJIBp7hoakouujluwJu0q5bCjpoyyzVR%2FGJ1UehMdOxAP43aXYEKvi81Zk8lice6uEHPlk%2FAefYbG2psj2iwqInAlDPip%2Fi1NOhFm7jS%2FYobhzKDAmkcvPxn6aF9pWOBhZH2HTvSHpOld%2BhQUjBzKkbEN%2BKQvu3CYf4cwUzUmZfanvcI0oifcKx%2BKVQH88jCuWWNorRanSbr4qRHKUk1wXPIbg1%2FipmJBPVhXh4ZPbyFkGwW027WECxi5XEXE9f2smrvgbBBPiqt%2FoJhNvLYJZTuI0HZ026LmiSxTxN2Mmv7ZYnUNwu0D8hBTxmhwfk%2FSoO9h8SW4hidC6StEPUuMo7ti3mapXDgG3gjKmOE8PV87DE4HM20GqyNjQGpZ9tEizYIyfw57MbLcDovkciSZZDisMnkdK4OjYuwjDuMGN8zJoTX1knMUmoErUMHPqAHXOhrXNqBNVtqDbFMO3cG9zQoscERMhIo9hpfgL%2F4VZFyRTVYqvIhe0nLe%2Byxi3eH8snmbU2s9%2FdlDM519%2BfsI41ecBkatHnQ774L8w5t6g6QU6tAEWFwyf6Qbqw1LnQRpvtE5aVcVCpIXwA%2BWj3nniliDI8%2FhCrIlDigADQ92z24tgzz%2BZYG0%2B%2Bd%2BeF%2FH45YkBGBkqnv9JN0h7nYWNPCKuBDHemDsxqZV3iy2UoqtkmnYBXRI6zsBLHfebMnEEgzUZpSD7Bn6QON8sb8IOJI5ckfn2hAT0NeCWV%2B2dKsDRCuqPaEYOour2xouaXclA3OWTmRBGe5XSwK%2BmtcGm%2BOnjkDQKRsizP8M%3D&X-Amz-Signature=2d7fcd4f22afd3801a8a84c361e9bd75ef2ff15881d92fe40ec45fb8109b7f72&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22practice_xor.pdf%22

In [0]:
# presentation 
<img src="">

In [0]:
np.random.seed(1)
X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y = np.array([[0,1,1,0]]).T
W1 = 2*np.random.random((3,4)) - 1
W2 = 2*np.random.random((4,1)) - 1

print (X)
print (y)
print (W1)
print (W2)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
[[0]
 [1]
 [1]
 [0]]
[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]
[[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]
 [ 0.34093502]]


In [0]:
lr = 0.5
#%%
for j in range(100): 
    ## Forward (60000 epoch)
    z1 = np.dot(X,W1) #      1) fully connected layer
    a1 = 1/(1+np.exp(-z1)) # 2) sigmoid activation
    z2 = np.dot(a1,W2) #     3)fully connected layer 
    a2 = 1/(1+np.exp(-z2)) # 4) sigmoid activation  
    # print(np.shape(z1))
    
    ## Backward (미분, backpropagation differenciate)
    dz2 = a2-y  # 6) 
    da1 = np.dot(dz2,W2.T)   # 7) 
    dW2 = np.dot(a1.T, dz2)  # 8) 
    dz1 = da1*(1-a1)*a1   # 9)
    dW1 = np.dot(X.T, dz1)  # 10)
    
    print(dW1)

[[ 0.00416057  0.02004408  0.01511367  0.00628397]
 [ 0.00077263  0.01616417  0.04057965  0.00164123]
 [-0.0033674   0.02489289  0.00765196  0.00179071]]
[[ 0.00416057  0.02004408  0.01511367  0.00628397]
 [ 0.00077263  0.01616417  0.04057965  0.00164123]
 [-0.0033674   0.02489289  0.00765196  0.00179071]]
[[ 0.00416057  0.02004408  0.01511367  0.00628397]
 [ 0.00077263  0.01616417  0.04057965  0.00164123]
 [-0.0033674   0.02489289  0.00765196  0.00179071]]
[[ 0.00416057  0.02004408  0.01511367  0.00628397]
 [ 0.00077263  0.01616417  0.04057965  0.00164123]
 [-0.0033674   0.02489289  0.00765196  0.00179071]]
[[ 0.00416057  0.02004408  0.01511367  0.00628397]
 [ 0.00077263  0.01616417  0.04057965  0.00164123]
 [-0.0033674   0.02489289  0.00765196  0.00179071]]
[[ 0.00416057  0.02004408  0.01511367  0.00628397]
 [ 0.00077263  0.01616417  0.04057965  0.00164123]
 [-0.0033674   0.02489289  0.00765196  0.00179071]]
[[ 0.00416057  0.02004408  0.01511367  0.00628397]
 [ 0.00077263  0.01616417

In [0]:
# prediction
X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
a1 = 1/(1+np.exp(-(np.dot(X,W1))))
a2 = 1/(1+np.exp(-(np.dot(a1,W2))))
print(a2)

[[ 0.47372957]
 [ 0.48895696]
 [ 0.54384086]
 [ 0.54470837]]
