In [1]:
import tensorflow as tf

In [2]:
placeholder = tf.placeholder(dtype = tf.float32, shape=[3,3])
Variables = tf.Variable([1,2,3,4,5], dtype = tf.float32)
constant = tf.constant([10,20,30,40,50], dtype = tf.float32)

In [3]:
image = [[1,3,4,5,6]
        ,[5,6,7,2,1]
        ,[10,20,30,40,50]]
label = [10,20,30,40,50]

ph_image=tf.placeholder(dtype = tf.float32)
ph_label=tf.placeholder(dtype = tf.float32)

feed_dict = {ph_image:image, ph_label:label}

result_tensor = ph_image + ph_label 

In [4]:
sess = tf.Session() 
result = sess.run(result_tensor, feed_dict = feed_dict)
print(result)

[[  11.   23.   34.   45.   56.]
 [  15.   26.   37.   42.   51.]
 [  20.   40.   60.   80.  100.]]


In [5]:
sess.close()

In [6]:
import tensorflow as tf


In [7]:
input_data = [[1,2,3,4,5,6,7]
             ,[9,1,2,3,6,7,0]]
label_data = [[0,0,0,1,0]
             ,[1,0,0,0,0]]

In [8]:
input_size = 7
hidden1_size = 10
hidden2_size = 8
classes = 5

learning_rate = 5e-2

In [9]:
x = tf.placeholder(tf.float32, shape = [None,input_size])
## 일반적으로 배치의 개수를 알지못해서 None값으로 지정
y_ = tf.placeholder(tf.float32, shape = [None,classes])

In [10]:
tensor_map = {x:input_data, y_: label_data}

In [11]:
W_h1 = tf.Variable(tf.truncated_normal(shape = [input_size, hidden1_size]), dtype = tf.float32)
b_h1 = tf.Variable(tf.zeros (shape = [hidden1_size]), dtype = tf.float32)

## truncated_normal : 가중치들은 이 함수로 초기화 되는데 이때 주어진 평균값과 표준편차에 따라 값을 만들어냄 
W_h2 = tf.Variable(tf.truncated_normal(shape = [hidden1_size, hidden2_size]), dtype = tf.float32)
b_h2 = tf.Variable(tf.zeros (shape = [hidden2_size]), dtype = tf.float32)

W_out = tf.Variable(tf.truncated_normal(shape = [hidden2_size, classes]), dtype = tf.float32)
b_out = tf.Variable(tf.zeros (shape = [classes]), dtype = tf.float32)

In [12]:
hidden1 = tf.nn.softmax(tf.matmul(x, W_h1) +b_h1)
hidden2 = tf.nn.softmax(tf.matmul(hidden1,W_h2) +b_h2)
y = tf.nn.softmax(tf.matmul(hidden2, W_out) +b_out)

## 활성함수 


In [13]:
cost = tf.reduce_mean(-y_*tf.log(y)-(1-y_)*tf.log(1-y))
train = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

In [14]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
print(sess.run(cost, feed_dict = tensor_map))

0.493155


In [15]:
sess.close()